services:
    gollum:
        image: gollumwiki/gollum:master
        ports:
            - "8880:4567"
        volumes:
            - ./wiki-data:/wiki
        environment:
            - GIT_AUTHOR_NAME=IvanPSG-BR
            - GIT_AUTHOR_EMAIL=ivan.psg@protonmail.com
            - GOLLUM_PARAMS=--allow-uploads
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: 256M
    tunnel:
        image: cloudflare/cloudflared:latest
        restart: unless-stopped
        network_mode: host
        command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
